name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install the latest Juvix compiler (for latest build-type)
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: anoma/juvix
          tag: latest
          chmod: 0755
      - name: See the dev version in the documentation
        id: juvix-version
        run: |
          echo "number=$(cat VERSION)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-juvix-plugin
      - run: mkdocs gh-deploy --force